version: '3'

services:
  frontend:
    image: teslo-shop-nextjs-image
    container_name: host-teslo-shop-frontend
    build:
      context: ./frontend
      dockerfile: ../provision/frontend/Dockerfile
    ports:
      - ${NEXT_PUBLIC_APP_PORT}:3000
    stdin_open: true
    tty: true
    networks:
      - main
    volumes:
      - ./frontend:/home/app

networks:
  main:
    driver: bridge
